#' Plot hierarchical shift function
#'
#' Plot hierarchical shift function generated with \code{\link{hsf}}.
#' The function returns a ggplot object, which can be
#' customised using the \href{http://docs.ggplot2.org/current/}{ggplot2}
#' package. Individual shift functions are superimposed in the background. The trimmed mean of the shift functions is plotted on top, with a confidence interval for each quantile.
#' A horizontal line indicates the null reference value entered in \code{hsf}.
#'
#' @references Rousselet, G. A., & Wilcox, R. R. (2019, January 17). Reaction
#'   times and other skewed distributions: problems with the mean and the
#'   median. https://doi.org/10.31234/osf.io/3y54r
#'
#' @param data A list generated by \code{\link{hsf}}.
#' @param viridis_option Viridis colour map for individual shift functions - default = "B".
#' @param ind_line_alpha Alpha transparency for individual shift functions - default = 0.5
#' @param ind_line_size Line thickness for for individual shift functions - default = 0.5
#' @param gp_line_colour Group line colour - default = "black".
#' @param gp_line_size Group line size - default = 1.
#' @param gp_point_colour Group point colour - default = "black".
#' @param gp_point_size Group point size - default = 0.5
#'
#' @return A ggplot object.
#'
#' @examples
#' plot_hsf(out) # default plot
#' p <- plot_hsf(out) # get ggplot object
#' plot_hsf(out, gp_line_colour = "purple", gp_point_colour = "purple") # pink group shift function
#'
#' @export
plot_hsf <- function(data,
                     viridis_option = "B",
                     ind_line_alpha = 0.5,
                     ind_line_size = 0.5,
                     gp_line_colour = "black",
                     gp_line_size = 1,
                     gp_point_colour = "black",
                     gp_point_size = 0.5
                     ){
  # check input is a list of data frames
  if(!is.list(data)){
    stop("data must be a list returned by hsf()")
  }
  if(length(data)!=8){
    stop("data must have length 8, as returned by hsf()")
  }

  np <- dim(data$individual_sf)[2] # number of participants
  df <- tibble(diff = as.vector(data$individual_sf),
               dec = rep(data$quantiles, np),
               participants = factor(rep(seq(1:np), each = length(data$quantiles))))

  df.gp <- tibble(diff = data$group_differences,
                  dec = data$quantiles,
                  ymin = data$ci[1,],
                  ymax = data$ci[2,])

  p <- ggplot(df, aes(x = dec, y = diff, colour = participants)) + theme_classic() +
    geom_line(alpha = ind_line_alpha, size = ind_line_size) +
    geom_abline(slope = 0, intercept = data$null_value) +
    geom_line(data = df.gp, colour = gp_line_colour, size = gp_line_size) +
    geom_pointrange(data = df.gp, aes(ymin = ymin, ymax = ymax),
                    colour = gp_point_colour, size = gp_point_size) +
    # geom_point(data = df.gp, colour = gp_point_colour) +
    scale_colour_viridis_d(option = viridis_option) +
    scale_x_continuous(breaks = data$quantiles) +
    # scale_y_continuous(breaks = seq(-500,700,250)) +
    # coord_cartesian(ylim = c(-500, 700)) +
    theme(legend.position = "none",
          plot.title = element_text(size = 22),
          axis.title.x = element_text(size = 18),
          axis.text = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 18)) +
    labs(x = "Quantiles", y = "Differences") +
    # ggtitle(paste0(data$comparison," quantile differences"))
    ggtitle(data$comparison)

  suppressMessages(p)
}
